title: Henry Pan
description: "I help Christian entrepreneurs grow their businesses through personal brands that actually reflect who they are."
url: "https://henrybpan.com"
baseurl: ""
markdown: kramdown
theme: null
permalink: pretty
plugins:
  - jekyll-redirect-from
exclude:
  - add.js
  - context.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
